### POST - Crear Comentario (A post)
POST http://localhost:8080/api/comments/posts/3
Content-Type: application/json

{
  "author": "Autor del comentario 4342",
  "content": "Contenido del comentario para el post 43234"
}

### GET - Obtener Comentarios
GET http://localhost:8080/api/comments

### GET - Obtener Comentario por ID
GET http://localhost:8080/api/comments/1


### PUT - Actualizar Comentario
PUT http://localhost:8080/api/comments/1
Content-Type: application/json

{
  "author": "Autor del comentario actualizado",
  "content": "Contenido del comentario actualizado"
}

### DELETE - Eliminar Comentario
DELETE http://localhost:8080/api/comments/1