### POST - Crear Comentario (A post)
POST http://localhost:8080/api/comments/posts/1
Content-Type: application/json

{
  "author": "{{$random.name.firstName}} {{$random.name.lastName}}",
  "content": "{{$random.lorem.sentence}}"
}

### GET - Obtener Comentarios
GET http://localhost:8080/api/comments

### GET - Obtener Comentario por ID
GET http://localhost:8080/api/comments/4


### PUT - Actualizar Comentario
PUT http://localhost:8080/api/comments/4
Content-Type: application/json


{
  "author": "Juan Perez",
  "content": "{{$random.lorem.sentence}}"
}

### DELETE - Eliminar Comentario
DELETE http://localhost:8080/api/comments/4