### POST - Crear Post
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "{{$random.book.title}}",
   "content": "{{$random.lorem.paragraph}}"


}

### GET - Obtener todos los posts
GET http://localhost:8080/api/posts

### GET - Obtener todos los posts con comentarios
GET http://localhost:8080/api/posts?withComments=true

### GET - Obtener post por ID
GET http://localhost:8080/api/posts/5

### GET - Obtener post por ID con comentarios
GET http://localhost:8080/api/posts/4?withComments=true

### PUT - Actualizar post por ID
PUT http://localhost:8080/api/posts/4
Content-Type: application/json

{
  "title": "Título Editado",
  "content": "{{$random.lorem.paragraph}}"
}

### DELETE - Eliminar post por ID
DELETE http://localhost:8080/api/posts/4